# Generated by Django 3.0.8 on 2020-08-14 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order', models.IntegerField(default=200)),
                ('coupon_type', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('hard_discount', models.IntegerField(default=0)),
                ('coupon_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(default=100)),
                ('item_rating', models.IntegerField(default=5)),
                ('item_image_url', models.CharField(max_length=1000)),
                ('item_genre', models.IntegerField(default=0)),
                ('item_veg', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Useraddress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='Where do we deliver ? ', max_length=1000)),
                ('pincode', models.IntegerField(default=400076)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_type', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='soul.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_freezed', models.IntegerField(default=0)),
                ('order_items', models.ManyToManyField(to='soul.FoodOrderItem')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('order_items', models.ManyToManyField(to='soul.FoodOrderItem')),
            ],
        ),
    ]
