# Generated by Django 3.0.8 on 2020-08-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_coupon',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='soul.Coupon'),
        ),
    ]
