# Generated by Django 3.0.8 on 2020-08-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soul', '0002_cart_discount_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='order_freezed',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='discount_coupon',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='soul.Coupon'),
        ),
    ]
