# Generated by Django 3.0.8 on 2020-08-15 11:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soul', '0003_auto_20200815_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='discount_coupon',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
